### ISSUE TITLE
Falldatenblatt - Arbeitsrecht/Arbeitsverträge

### ISSUE THREAD

**Issue by RA-crm** [jlawyerorg/j-lawyer-forms#1]
Die Falldatenblätter können insbesondere bei der Erstellung standardisierter Texte und Schriftsätze helfen. Hierzu können typische in dem jeweiligen Rechtsgebiet anfallenden Informationen in der Akte selbst gepflegt werden, um darauf aufbauend etwa Klagen, Forderungsschreiben oder Deckungsanfragen zu erstellen.

Für das Arbeitsrecht/Arbeitsverträge schlage ich vor:

Arbeitgeber:									Arbeitnehmer:
Name/Firma									Name, Vorname
Anschrift									Anschrift

Geschlossen am:		___
Gekündigt am: 		___			___ ordentlich	___ außerordentlich 		__Probezeit
Grund:

mtl. Vergütung (fest):	___
Zuschläge:			___	
Provisionen:			___

Urlaubstage (lt. Vertrag): ___			___	 verbraucht			___  nicht verbraucht

**Comment by PBaumfalk** [comment]
Betriebsrat (ja/nein)
mehr als 5 Mitarbeiter
mehr als 10 Mitarbeiter
Schwerbehinderung (ja/nein)
Mutterschutz (ja/nein)
Betriebsratsmitglied (ja/nein)
Datenschutzbeauftragter (ja/nein)

Und am Ende würde ich die Standardfragen noch abfragen für den Mandanten:
Soll außergerichtlich eine Einigung erzielt werden?
Weiterbeschäftigung gewünscht? (für den Weiterbeschäftigungsantrag)
Zwischenzeugnis einklagen?
Einsicht in die Personalakte gewünscht?

**Comment by PBaumfalk** [comment]
Wir haben für die KSchG-Geschichten mal ein Falldatenblatt entwickelt:
![fnnilohpeccnednp](https://user-images.githubusercontent.com/50404378/96462382-cb5ea700-1225-11eb-9eb2-0bbeed2980eb.png)
![eiaegflklkkadkpg](https://user-images.githubusercontent.com/50404378/96462390-cd286a80-1225-11eb-8732-2a4fef24faf1.png)
