### ISSUE TITLE
[BUG] Berechnung Differenzbesteuerung Verkehrsunfalldaten fehlerhaft

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-forms#108]
Die Differenzbesteuerng wird mE falsch gerechnet. Rückgerechnet ergeben netto 97,50€ differenzbesteuert brutto 99,94€. Hier müsste gerechnet werden: Bruttobetrag - (Bruttobetrag/1,025). Gerechnet wird: Bruttobetrag*0,025
![image](https://user-images.githubusercontent.com/77149788/208882310-53ceedad-f906-4c37-945c-232b865b6911.png)

Die Regelbesteuerung ist vergleichsweise korrekt:
![image](https://user-images.githubusercontent.com/77149788/208882180-3cba5b36-6be9-439c-9afa-308db60701ec.png)

**Comment by j-dimension** [comment]
@Linkki2021 hier fehlt mir Expertise. Die Person, die bei der ursprünglichen Erstellung des Falldatenblattes fachlich unterstützt hat, schrieb damals:

> Totalschaden 
> Bei einem Totalschaden stellt sich die Situation etwas anders dar. Der Sachverständige ermittelt einen Wiederbeschaffungswert. In zwei Fällen enthält dieser Wert bereits eine Mehrwertsteuer, die gegebenenfalls herausgerechnet werden muss. In einem Fall ist keine Mehrwertsteuer enthalten. Dies hängt vom Fahrzeug ab, und zwar, ob es gewöhnlich regelbesteuert (bei neueren Fahrzeugen), differenzbesteuert (ältere Fahrzeuge, die noch von Gebrauchtwagenhändlern verkauft werden) oder steuerneutral (nur noch auf dem Privatmarkt verkäuflich). Bei der Regelbesteuerung sind im Wiederbeschaffungswert 19 % Mehrwertsteuer enthalten (Beispiel: Wiederbeschaffungswert 11.900,- € = 1.900,- € Mwst.). Die Formel müsste also lauten Mehrwertsteuer = Wiederbeschaffungswert x (1 – 1/1,19). Die Differenzbesteuerung bedeutet, dass nur die Gewinnmarge des Händlers mit 19 % besteuert wird. Geschätzt sind das ca. 2,5 % des Wiederbeschaffungswertes. Beim oben genannten Beispiel von 11.900 € wären das 297,50 € MwSt. Bei steuerneutralen Fahrzeugen ist die Mehrwertsteuer naturgemäß 0 €. 

Kannst Du damit etwas anfangen?

**Comment by Linkki2021** [comment]
Hallo Jens,

anfangen kann ich damit schon etwas, die Erläuterung zur Differenzbesteuerung ist generell richtig.

Für die Bezifferung des durch den Anwalt vertretenen Geschädigten bleibt es dennoch falsch, den interessiert ja der Weiterverkauf durch den Händler nicht. 11.900 ist der Bruttowert, entweder sind da 19% USt. drin, oder 2,5%. Die Formel muss also immer gleich sein.

**Comment by j-dimension** [comment]
@Linkki2021 ich habe jetzt eine Änderung umgesetzt. Bitte mal das Falldatenblatt updaten, testen und hier Rückmeldung geben. Danke!

**Comment by Linkki2021** [comment]
Schaut gut aus! Danke!
