### ISSUE TITLE
Verkehrsunfalldaten: Nutzungsausfall editierbar

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-forms#133]
Händische Eingabe des Tagessatzes.

Die händische Eingabe kann man z.B. gebrauchen, wenn nur Vorhaltekosten statt Nutzungsausfall erstattet wird. Außerdem sind die Ausfallgruppen abhängig vom Fahrzeugalter, sodass die Sachverständigen manchmal die Ausfallgruppe mit oder ohne Berücksichtigung des Fahrzeugalters bennenen. Das führt dazu, dass z.B. ein Fahrzeug in der Gruppe "E" (43,00 € am Tag) manchmal noch einen Abschlag aufgrund des Fahrzeugalters bekommt. Richtig wäre es dann, das Fahrzeug in die nächstniedrigere Gruppe zu gruppieren - das machen aber nicht alle Sachverständigen so konsqequent. Daher ist es es besonders wichtig, den Tagessatz sehen zu können und es wäre ganz gut, daran selbst "herumdrehen" zu können. Darüber hinaus kann man das Falldatenblatt dann auch für andere Tagessätze einsetzen, z.B. bei Taxifahrern mit bezifferbarem entgangenen Gewinn oder bei bestimmten Nutzfahrzeugen.

- [x] Eingabemöglichkeit schaffen
- [x] bisherige Auswahl wird zwecks Vorbelegung des Feldes genutzt
- [x] Berechnung jedoch einzig auf Basis des (editierbaren) Feldes

**Comment by j-dimension** [comment]
@Linkki2021 kannst Du hier mal drüberschauen? Ist ein Wunsch eines Users, und ich möchte ausschließen dass Ihr davon "negativ betroffen" seid.

**Comment by Linkki2021** [comment]
Über das Thema kann man mE diskutieren. Grundsätzlich ist der Nutzungsausfall in dem Themenumfeld, solange man nicht nur Spezialmandanten bedient (Busbetreiber, Nutzfahrzeugflotten zB), aber der klare Standard, man sollte die Maske also nicht zu sehr für das Thema verbiegen.

Das beschriebene Abschlagproblem ist aus meiner Sicht keines wenn ich es richtig verstanden: bei Bedarf einfach die darunterliegende Klasse wählen, fertig.

Man könnte von meiner Warte aus darüber nachdenken, ob man quasi eine Auswahl schafft: Nutzungsausfall oder Vorhaltekosten/Tagessatz. Im ersten Fall bleibt alles so, wie es ist. Für den zweiten Fall schafft man oben eine individuelle Eingabezeile und unten eine weitere Zeile Vorhaltekosten, die sich aus Datumsangaben und dem Tagessatz ergibt. 

Es gibt heute bereits das Feld "Verrechnungssatz", was kann das?

**Comment by j-dimension** [comment]
@Linkki2021: Gruppe ist abhängig vom Fahrzeugalter, aber dann würde man lediglich die Gruppe anpassen, nicht den Betrag - wäre inhaltlich zu klären.

**Comment by j-dimension** [comment]
FB: Vorhaltekosten über diese Änderung abbildbar
