### ISSUE TITLE
Verkehrsunfalldaten: Wiederbeschaffungsaufwand hinzufügen

### ISSUE THREAD

**Issue by j-dimension** [jlawyerorg/j-lawyer-forms#134]
neue Zeile im Falldatenblatt, direkt unter den Wiederbeschaffungswerten und Restwerten, bspw. so:

![jfx17503136078723676893](https://github.com/jlawyerorg/j-lawyer-forms/assets/3729754/0ac0af13-7c77-4728-83ea-2476515cb029)

Es sollen zwei Szenarien ermöglicht werden:

1. Eingabe WBW und Restwert --> WBA berechnen
2. Eingabe WBA und Restwert=0 (@Linkki2021 "WBA ist ja immer WBW - Restwert" - klären)

Es müssten also

- [ ] WBA als Platzhalter bereitgestellt werden
- [ ] WBA berechnet werden (Variante 1)
- [ ] Die Berücksichtigung / Berechnung im "Gesamtschaden" so geändert werden, dass sie ausschließlich auf Basis des WBA funktioniert

**Comment by j-dimension** [comment]
@Linkki2021 kannst Du hier mal drüberschauen? Ist ein Wunsch eines Users, und ich möchte ausschließen dass Ihr davon "negativ betroffen" seid.

**Comment by Linkki2021** [comment]
Hallo Jens, grundsätzlich nicht verkehrt, erhöht die Übersichtlichkeit.

Spalte Werte lt. Versicherer mE überflüssig, das trägt man in reguliert ein, dann kommt es aufs Gleiche raus.

Szenario 2 verstehe ich nicht: wenn ich einen WBW eingebe und der RW=0 ist, dann ist in dem Fall WBW=WBA, und alles ist gut. ME muss der WBA für sich nicht editierbar sein sondern ist eine reine Ausgabe von WBW-RW.

ToDo-Checkbox3 entfällt mE. Du berechnest die summierte Schadenposition bereits heute als WBW-RW(=WBA).

P.S.: Das Rechenbeispiel ist falsch. 6500-1500=5000, und die Differenz damit =1000€. Auch das hast Du bereits heute, ohne es geprüft zu haben, wenn Du die entsprechenden Werte einträgst - solange Auswahl=steuerneutral.

**Comment by j-dimension** [comment]
@Linkki2021 "WBA berechnen und als Platzhalter bereitstellen"
