### ISSUE TITLE
Verkehrsunfalldaten: Preset Unfallpauschale

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-forms#137]
Kann das Preset entweder auf 30€ gestellt oder rausgenommen werden?

Die derzeitigen 25€ sind nur bedingt hilfreich, viele in diesem Bereich tätige Kanzleien fordern hier mittlerweile 30€.

Wenn es standardmäßig auf 0 stehen würde ist das die flexibelste Lösung.

**Comment by j-dimension** [comment]
@Linkki2021 hab das standardmäßig auf 30 EUR gesetzt.
