### ISSUE TITLE
Verkehrsunfalldaten: 6 Monate Haltefrist in 100 % Fällen direkt eintragen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-forms#17]
durch die Angabe des Unfalldatums könnte in einem Feld direkt eine automatische Berechnung erfolgen (+6 Monate). Das Datum könnte sich dann als Platzhalter verwenden lassen.

**Comment by j-dimension** [comment]
Geht es um diesen Sachverhalt? https://verkehrslexikon.de/Module/Fiktiv6Monate.php

Und soll es eine reine Anzeige sein? Oder als Platzhalter zur Verfügung stellen?

**Comment by iradraconis** [comment]
Ja genau darum geht es. 

Als Platzhalter könnte das Datum jedenfalls in den Schriftsatz an die Versicherung aufgenommen werden. Die reine Anzeige wäre aber auch schon ok. 

Kann denn das Falldatenblatt vielleicht auf Knopfdruck auch eine Frist in die Akte eintragen?

**Comment by j-dimension** [comment]
@iradraconis @Linkki2021 wie sollte diese Frist lauten?

**Comment by iradraconis** [comment]
Das Unfalldatum wird ja bereits durch den Nutzer angegeben. Der Nutzer könnte also gefragt werden, ob der Mandant das Fahrzeug teilrepariert und mindestens 6 Monate weiter nutzen möchte. Daraufhin könnte automatische eine Frist berechnet werden, und zwar sechs Monate ab dem Unfalldatum. Vielleicht könnte auch so wie bei den Betreuungsfalldaten automatisch eine Frist im Kalender eingetragen (angeboten) werden.

(Die Haltefrist wird dann relevant, wenn rein rechnerisch gesehen ein Totalschaden vorliegt, Die Versicherung also den Wiederbeschaffungsaufwand ersetzt (Wiederbeschaffungswert minus Restwert), der Geschädigte aber nach Ablauf von sechs Monaten die Differenz zwischen WBA zu den netto Reparaturkosten verlangen kann, wenn er das Fahrzeug weiterhin nutzt. Der Anwalt muss nach sechs Monaten wieder tätig werden, da viele Versicherungen diese Differenz erst nach Ablauf von sechs Monaten zahlen)

**Comment by j-dimension** [comment]
@iradraconis Danke, mir ging es um die eigentliche Formulierung. Soetwas wie

"Ablauf Haltefrist"

o.ä.

**Comment by Linkki2021** [comment]
Ablauf Haltefrist klingt gut für mich

**Comment by iradraconis** [comment]
> @iradraconis Danke, mir ging es um die eigentliche Formulierung. Soetwas wie
> 
> "Ablauf Haltefrist"
> 
> o.ä.

Sorry 🤭 
Ja Ablauf Haltefrist klingt gut. Vielleicht besser: Ablauf 6 Monate Haltefrist

**Comment by j-dimension** [comment]
Wird mit der nächsten j-lawyer - Version veröffentlicht, da Code enthalten ist für den ich ein Clientupdate benötige.

**Comment by j-dimension** [comment]
Hier mal ein Video wie das dann ausschaut:

https://user-images.githubusercontent.com/3729754/126844946-72b62b4c-24d2-4649-8c11-c0c3aab151cb.mp4
