### ISSUE TITLE
Falldatenblatt: Inkasso

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-forms#3]
Siege oben. Ggf. eine gute Vorbereitung zur Erstellung der EDA Datei

**Comment by RA-crm** [comment]
siehe auch https://github.com/jlawyerorg/j-lawyer-org/issues/756 
m.E. passt Inkasso zur Frage Forderungskonto

**Comment by j-dimension** [comment]
Weiß jemand wo der Inhalt / das Dateiformat der EDA-Dateien beschrieben ist? Tue mich gerade schwer etwas zu finden.

**Comment by PBaumfalk** [comment]
https://www.mahngerichte.de/de/elektronischer-datenaustausch.html

**Comment by PBaumfalk** [comment]
Wir haben ein Falldatenblatt zu Inkasso fertig. Wir würden das als Beta für die Version 1.13 hier zur Diskussion und zur Verfügung stellen.

**Comment by PBaumfalk** [comment]
Hier ist ein Screenshot:

![image](https://user-images.githubusercontent.com/50404378/96225119-e664b900-0f90-11eb-919b-856894366c1f.png)

**Comment by j-dimension** [comment]
Große Klasse! Die Falldatenblätter können von mir unabhängig von einem Release bereitgestellt werden. Also immer her damit.

**Comment by PBaumfalk** [comment]
Wir fummeln hier gerade noch.

Mit freundlichen Grüßen / Kindly Regards

Patrick Baumfalk
Rechtsanwalt / Lawyer


Mobil:    +49 1525 53 04 194
E-Mail:   patrick.baumfalk@kanzlei-baumfalk.de


Baumfalk - Rechtsanwaltskanzlei
Hauptstr. 195
50169 Kerpen

Tel.: +49 2273 40 68 504
Fax: +49 2273 59 03 565

E-Mail: info@kanzlei-baumfalk.de
Web: www.kanzlei-baumfalk.de

**Comment by PBaumfalk** [comment]
Wie können wir denn den Quellcode hier bereitstellen?

**Comment by j-dimension** [comment]
Kann dein MA mit Git umgehen? Wenn Ihr mehr oder weniger regelmäßig Änderungen macht, dann wäre das die "saubere" Variante, die aber etwas Kenntnisse voraussetzt.

Ansonsten die einfache Variante: per Mail an mich und ich pflege es ein.

**Comment by PBaumfalk** [comment]
Könntest du uns das mit dem GIT erklären, wie wir da was pushen können?

**Comment by j-dimension** [comment]
@PBaumfalk  Ja, wollen wir das als Telko / per AnyDesk machen? Dann würde ich mal zwei / drei Terminvorschläge schicken.

**Comment by PBaumfalk** [comment]
@j-dimension Ja, gerne. Bitte kurz mit Christian das machen. Der erstellt sich mal einen Git-Account.
