### ISSUE TITLE
Falldatenblatt Familienrecht

### ISSUE THREAD

**Issue by SaschaKarcher01** [jlawyerorg/j-lawyer-forms#34]
Anbei ein Dokument, wie ein Familienrechtsdatenblatt aussehen könnte. 
[Fragebogen Familienrecht.pdf](https://github.com/jlawyerorg/j-lawyer-forms/files/5970992/Fragebogen.Familienrecht.pdf)

**Comment by j-dimension** [comment]
Abschnitt "Hochzeit": 

![grafik](https://user-images.githubusercontent.com/3729754/107823116-81bf3c80-6d7f-11eb-8541-8a6e44d12c35.png)

**Comment by j-dimension** [comment]
Abschnitt "Trennung":

![grafik](https://user-images.githubusercontent.com/3729754/107823169-a0bdce80-6d7f-11eb-8b11-25eb5c3632fc.png)

**Comment by j-dimension** [comment]
Abschnitt "Scheidung": 

![grafik](https://user-images.githubusercontent.com/3729754/107823227-baf7ac80-6d7f-11eb-9511-7c1b8a842294.png)

**Comment by j-dimension** [comment]
verfügbare Platzhalter:

![grafik](https://user-images.githubusercontent.com/3729754/107823322-e084b600-6d7f-11eb-9a72-18d0f73b838b.png)

**Comment by Kargoscha** [comment]
Im Prinzip hat das Datenblatt alles. Allerdings hat mein eigenes Datenblatt einige bewährte Zusätze:
stimmt der Ehepartner der Scheidung zu:
Soll der Versorgungsausgleich ausgeschlossen werden (Versorgungsausgleich geklärt?)
Jetzige Staatsangehörigkeit: 
Staatsangehörigkeit z.Zt. der Heirat:
Geburtsname:
Beruf:
Geburtsort des Kindes:
bei minderjährigen Kindern, Wohnort bei welchem Elternteil:
Liegt ein notarieller Vertrag vor:
sichere Postadresse:
sichere e-mail-Adresse:
sichere Telefonnummer: 

In Famieliensachen gibt es nur VKH (Verfahrenskostenhilfe) keine PKH

VG
Alexander Kargoscha

**Comment by j-dimension** [comment]
@Kargoscha vielen Dank für das Feedback!

Wenn Du die zusätzlichen Angaben in die logischen "Abschnitte" oben einteilen könntest, oder ggf. einen zusätzliche Abschnitt definieren kannst, dann werde ich das kurzfristig noch hinzufügen.

**Comment by Kargoscha** [comment]
Ich bräuchte dafür die pdf als Writer -datei, dann könnte ich die Zusätze einrücken. vorab aber dies hier
[Fragebogen.Familienrecht-Zusaetze.pdf](https://github.com/jlawyerorg/j-lawyer-forms/files/5976531/Fragebogen.Familienrecht-Zusaetze.pdf)

**Comment by j-dimension** [comment]
@Kargoscha die liegt mir selbst nicht vor. 

@SaschaKarcher01 kann evtl. die ursprünglich bereitgestellte Datei als ODT / DOCX bereitgestellt werden? Vielen Dank!

**Comment by SaschaKarcher01** [comment]
odt geht unter github leider nicht. Habe es in docx gewandelt. Hoffe Formatierungen passen dann soweit.
[Fragebogen Familienrecht.docx](https://github.com/jlawyerorg/j-lawyer-forms/files/5977875/Fragebogen.Familienrecht.docx)

**Comment by Kargoscha** [comment]
Und zurück, mit den Änderungen (in blau markiert)

Vg

Alexander Kargoscha

Am 14.02.2021 um 15:26 schrieb SaschaKarcher01:

**Comment by j-dimension** [comment]
> Und zurück, mit den Änderungen (in blau markiert)

Alexander @Kargoscha ich finde leider keinen Anhang mit den Änderungen - kannst Du es nochmal direkt über die Github-Oberfläche dazuladen? Danke!

**Comment by Kargoscha** [comment]
[Fragebogen.Familienrecht.docx](https://github.com/jlawyerorg/j-lawyer-forms/files/5978633/Fragebogen.Familienrecht.docx)

**Comment by j-dimension** [comment]
@SaschaKarcher01 @Kargoscha ich habe nun (fast) alle Änderungen eingearbeitet und eine neue Version des Falldatenblattes bereitgestellt. 

Eine Frage zu den "persönlichen Angaben": wäre das nicht eine Dopplung zur Erfassung eines Beteiligten?

**Comment by j-dimension** [comment]
PS: Der Platzhalter FAMR_SCH_PKH wurde umbenannt in FAMR_SCH_VKH. Bereits erfasste Falldatenblätter haben an dieser Stelle keinen definierten Wert mehr, ggf. den Haken neu setzen.

**Comment by Kargoscha** [comment]
ja, es kann sich um eine Doppelung handeln. Allerdings geht es hier um sichere Verbindungen, auch wenn die Ehepartner unter einem Dach leben. Man kann das ja "besonders gessicherte Telefonnummer etc nennen.

**Comment by Maz111111** [comment]
Ich habe unterschiedliche Vordrucke für die Fälle, in denen erst ein Trennungsjahr abgelaufen ist und für die Fälle in denen bereits drei Trennungsjahre abgelaufen sind. Kann man dazu eine "Berechnung" einfügen, so dass anhand des Ergebnisses entweder der eine oder der andere Textbaustein gesetzt wird?

Ähnliches gilt für die Fragen gibt es Kinder oder nicht. Wenn ja bestimmt sich die Zuständigkeit des Gerichtes regelmäßig nach dem Wohnort der Kinder und wenn nicht nach dem letzten Ehewohnsitz, so dass in Abhängigkeit von der Beantwortung der Frage, jeweils ein andere Textbaustein gewählt werden muss bzw. ein anderer Vordruck.

Bei der Frage nach der Zustimmung zum Antrag sieht es auch so aus, dass eine Ablehnung anderen Vortrag benötigt.

Keine Ahnung ob das geht. Ich wüsste jetzt nicht mal ob, geschweige denn wie.

Herzliche Grüße
Martin

**Comment by j-dimension** [comment]
@Maz111111 da bräuchte ich etwas mehr Information.

Lassen sich diese "Berechnungen" in der Form wenn-dann formulieren? Bspw.

Wenn <x im Falldatenblatt eingetragen> dann stelle einen Langtext mit Wert <Text...> als Platzhalter A bereit, anderenfalls stelle einen anderen Wert <Text alternativ...>  als Platzhalter > bereit.

**Comment by Maz111111** [comment]
Ja - das müsste bei fast allem klappen.

Bsp:
Es gibt Kinder und diese wohnen bei EF
Dann Textbaustein:  "Die örtliche Zuständigkeit des Gerichts folgt aus § 122 Nr. 1 FamFG. Der / Die Antragsteller / in wohnt mit den gemeinschaftlichen Kindern unter der im Rubrum benannten Adresse. (ich habe unterschiedliche Vorlagen für Antrag er mit VKH; er ohne VKH; sie mit VKH, sie ohne VKH - je nachdem och ihn oder sie als Antragsteller/in vertrete).
Es gibt keine Kinder 
dann (von recht seltenen Ausreißern mal abgesehen)
"Die örtliche Zuständigkeit des Gerichts folgt aus § 122 Nr. 3 FamFG. Die Eheleute hatten ihren letzten gemeinschaftlichen Wohnsitz unter FAMR_TR_LETZTWOHN.

Trennungszeitraum
1Jahr:
Nach § 1566 Abs. 1 BGB wird unwiderlegbar vermutet, dass die Ehe gescheitert ist, wenn die Eheleute seit einem Jahr getrennt leben und beide die Scheidung der Ehe übereinstimmend wollen. So liegt es hier.

schon drei Jahre:
Nach § 1566 Abs. 2 BGB wird unwiderlegbar vermutet, dass die Ehe gescheitert ist, wenn die Eheleute seit drei Jahren getrennt leben. So liegt es hier.

Die Textbausteine sollten für jeden RA inhaltlich frei definierbar sein, da jeder seine Vorlieben in der Formulierung hat.

Wenn der andere nicht zustimmt (was meistens bei Mandatsannahme unbekannt ist) bräuchte man einen völlig anderen Vortrag - mithin vordruck.

**Comment by Dickmaulruessler** [comment]
Das ist eine schöne nerdige Idee... klingt mir aber fast schon nach einer eigenen "Legal Tech"-Anwendung ... 

@Maz111111 möchtest du dich, ggf. nach ein paar allgemeinen Hinweisen des "Chefs" zur empfohlenen Vorgehensweise, da nicht selbst hereinfuchsen?

**Comment by Maz111111** [comment]
Wenn die Falldatenblätter eine solche Funktionalität nicht von Hause aus mit sich bringen, dann geht es eben nicht.

Ich weiß nur einfach nicht, ob die Falldatenblätter das könnten.

@Dickmaulruessler grundsätzlich bin ich für so Nerdkram und "IT do it yourself" super zu haben und kann mich da auch echt "reinfuchsen"
Derzeit und auf lange Sicht verwende ich meine Freizeit aber darauf, ein Kleinkind davon abzuhalten, die Weltherrschaft an sich zu reißen oder damit den deswegen fehlenden Schlaf nachzuholen. 

Also @reinfuchsen - eher nein... ;-)

ein workaround sind dann eben unterschiedliche Vorlagen für jeden Fall oder eine begrenzte Anzahl an Vorlagen, in denen die Textbausteine schon drin stehen und je nach Fall von Hand gelöscht werden.

Das Falldatenblatt an sich nimmt ja so schon richtig viel Arbeit ab - 

VIELEN DANK DAFÜR ÜBRIGENS AN DEN ERSTELLER @SaschaKarcher01 UND ALLE MITWIRKENDEN!!!

**Comment by SaschaKarcher01** [comment]
Ich denke der Dank gehört allein @Jens Kutschke.

Leider scheinen wir alle die Onlineschulung zu den Falldatenblättern verpasst zu haben.
Soweit ich die Folien dazu durchgelesen habe, scheint es wenn man sich da einmal reinfuxt, nicht schwer zu sein,
wobei für Berechnungen etc. wahrscheinlich dann doch java/groovy Grundlagen nötig sind.

Wenn es um einfache Funktionen geht, wie VKH im Text einblenden, kann man auch einfach in Libre Office-Feldbefehl eine if-dann Kombi einfügen, beispielsweise if VKH=ja, dann ich beantrag für den Mandanten unter Beiordnung des Unterzeichners Verfahrenskostenhilfe.

Leider kann man anscheinend in libreOffice innerhalb des Befehls keine Platzhalter mehr verwerten. Insofern müsste man sich dann dauerhaft doch mal in die Falldatenblätter reinfuchsen.

Vielen dank allen für die Arbeitserleichterung

**Comment by Maz111111** [comment]
Ich dachte @SaschaKarcher01 hätte das Datenblatt programmiert und wäre der Ersteller.

**Comment by Dickmaulruessler** [comment]
> 
> Wenn die Falldatenblätter eine solche Funktionalität nicht von Hause aus mit sich bringen, dann geht es eben nicht.
> 

Nein, "von Haus aus" gibt es hier leider gar nichts. 

Nahezu alles hier ist fleißige nächtliche Handarbeit von @j-dimension (der soweit ich weiß sich tagsüber auch der Kindererziehung widmen muss) oder von anderen fleißigen Helfern...

**Comment by j-dimension** [comment]
@Kargoscha ich habe den Abschnitt "persönliche Angaben" nun noch hinzugefügt. Es gibt bereits eine neue Version 1.1 des Falldatenblattes zum Download.

An der Stelle schließe ich auch erstmal das Ticket. 

Die Weiterentwicklung hin zu einer "intelligenten Vorlage" wie von @Maz111111 vorgeschlagen ist sinnvoll, aber aufgrund des Umfangs nicht im Rahmen dieses Tickets umzusetzen. 

Hier sei auch auf ticket https://github.com/jlawyerorg/j-lawyer-org/issues/1078 verwiesen. 

Grüße und Danke an alle!
