### ISSUE TITLE
BUG - Falldatenblatt Arbeitsrecht und Inkasso kann nicht geladen werden

### ISSUE THREAD

**Issue by PBaumfalk** [jlawyerorg/j-lawyer-forms#58]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/50404378/118121500-df503d00-b3f1-11eb-99c4-9f48b81921b5.png">

**Comment by j-dimension** [comment]
Sieht aus wie ein Konflikt zwischen den ursprünglich von Euch entwickelten Falldatenblättern und jenen die zentral bereitgestellt werden. 

Kann ich client.log und server.log haben? (per E-Mail)
