### ISSUE TITLE
Fehler Anwaltskosten Falldaten Verkehr

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-forms#65]
Im Falldatenblatt Verkehrsunfall gibt es mE einen Berechnungsfehler bei den Anwaltskosten. Bei Streitwerten unter 500€ beträgt die VV7002 für die Vorverfahren Auslagen nur 12,74€. Es werden aber die für höhere Streitwerte anzurechnenden 20€ veranschlagt.

Dadurch stimmen dann sowohl Steuer als auch Endbetrag nicht. Zur Verdeutlichung zwei Screenshots aus dem Rechner-Plugin, dort ist es korrekt.

![image](https://user-images.githubusercontent.com/77149788/125074999-589ca100-e0be-11eb-933b-9af8796da4d5.png)
![image](https://user-images.githubusercontent.com/77149788/125075073-6eaa6180-e0be-11eb-8ae7-7a53f6f79a6a.png)

**Comment by j-dimension** [comment]
Hallo @Linkki2021 , der Auftraggeber (das Falldatenblatt war in erster Version eine Auftragsentwicklung) meint: "kommt praktisch nicht vor, man kann immer pauschal VV7002 20 EUR ansetzen"

Ob das tatsächlich so ist weiß ich nicht, mir erschien es damals plausibel. Haben anwaltlich behandelte Unfälle mit Gegenstandswert < 500 EUR? Dann müsste ich das anpassen.

**Comment by Linkki2021** [comment]
Hallo Jens, ist sicher nicht die Regel, die Streitwerte liegen normalerweise drüber. Es gibt aber Konstellationen, in denen es vorkommt, beispielsweise wenn Restsummen aus vorherigen Kürzungen außergerichtliche behandelt werden, oder im Bereich der Schmerzensgelder aus Verkehrsunfallschäden.

Insgesamt kein schlimmer Bug, insbesondere da ja zu viel statt zu wenig ausgegeben wird ;), aber eben auch nicht korrekt.

**Comment by j-dimension** [comment]
@Linkki2021 sollte jetzt behoben sein. Kannst Du mal Version 2.3.3 des Falldatenblattes installieren und drüberschauen?

**Comment by Linkki2021** [comment]
Sieht super aus, vielen Dank!
