### ISSUE TITLE
Falldatenblätter - programmieren und testen ohne Kopfschmerzen?

### ISSUE THREAD

**Issue by GuidoBo** [jlawyerorg/j-lawyer-forms#70]
Derzeit editiere ich mein Falldatenprojekt, speichere es, lösche die alte Version davon aus der Akte, installiere meine neue, geänderte Version und kann dann schauen, ob das funktioniert hat. Das ist nicht unbedingt smooth. Das PDF [Entwicklung von Falldatenblättern fürj-lawyer.org](https://cloud.j-dimension.com/index.php/s/o6Y92SCcYbk7CTT#pdfviewer) kenne ich:

- Gibt es einen Weg, die Änderungen an den Falldatanblättern unmittelbar beim Programmieren zu testen; wenigstens in puncto Syntax? Wie macht ihr das?
- Aktuell muss ich raten, was wohl falsch gelaufen sein könnte (es ist nicht immer die sch*** Groovy/Java-Syntax). Das ist wie mit verbundenen Augen auf Entenjagd zu gehen. Gibt es einen Weg, wenigstens **Fehlermeldung des Falldatenblatts** zu sehen?

Sagen wir es gibt Sprachen, die ich liebe, solche, die ich ok finde und es gibt Java. Bitte entschuldigt meinen wahrscheinlich arg genervten Subtext; die Lernkurve ist gerade extrem ermüdend.

**Comment by j-dimension** [comment]
Ich benutze eine ausgewachsene Entwicklungsumgebung dazu, habe aber mal ein kleines Tool für eine Kanzlei entwickelt, die auch Falldatenblätter schreibt. Sieht so aus (unten). Fehlermeldungen bekommt man direkt als Ausgabe, kann Änderungen am Code machen und "Ausführen" klicken und sieht sofort das resultierende Falldatenblatt.

![grafik](https://user-images.githubusercontent.com/3729754/134699289-8f37b983-76ca-4e7d-8dd3-4099f9a39ead.png)

**Comment by j-dimension** [comment]
Im Downloadportal unter "Tools" liegt eine .jar - Datei, die einfach in den Ordner mit den Groovy-Skripten kopieren und starten (Doppelklick reicht, wenn java installiert ist).

**Comment by j-dimension** [comment]
Limitation: wenn irgendwelche Funktionalität im Client / Server gerufen wird, geht das in diesem Tool nicht, da es "allein" steht. Aber für das Layouting etc. sollte das wirklich helfen.

**Comment by iradraconis** [comment]
ist das Tool mit der Client Version 2.1 inkompatibel? Bei mir werden nur Fehlermeldungen ausgeworfen, wenn ich das Tool in den entsprechenden Ordner kopiere und die Groovy Dateien "ausführen" möchte.

Gibt es vielleicht einen Tipp für "Hobbyprogrammierer" wie mich, wie man eine IDE am besten einrichtet und mit dem "Client" verbindet, damit produktiv Falldatenblätter erstellt oder "bearbeitet" werden können? Du benutzt ja Netbeans. Vielleicht gibt es Musterprojekt, so dass man sich da irgendwie reinfuchsen kann?

**Comment by j-dimension** [comment]
@iradraconis kannst Du die Fehlermeldung bereitstellen?

**Comment by iradraconis** [comment]
im wesentlichen Import-Fehler, kommt per Mail.
