### ISSUE TITLE
Verkehrsunfalldaten: freie Zeile manuell hinzufügen

### ISSUE THREAD

**Issue by iradraconis** [jlawyerorg/j-lawyer-forms#8]
Momentan gibt es einen Posten "sonstige". Es wäre toll, wenn der Nutzer selbst mehrere Zeilen hinzufügen könnte.
So wären zahlreiche Angaben zu dem ohnehin fehlenden Personenschaden möglich, wie zum Beispiel "beschädigte Kleidung", "Besuchskosten Angehöriger", "vermehrte Bedürfnisse" etc. Die Liste kann lang werden. 

Diese Posten individuell eingeben zu können, ließe sich unter Berücksichtigung der Standardposten vielleicht am ehesten bewerkstelligen, in dem eine bzw. mehrere Zeilen frei hinzugefügt werden könnten, z.B. mit einem + Button oder so? Und die jeweilige Zeile müsste individuell zu benennen sein.

Momentan sind weitere Posten gesondert aufzuführen, z.B. in einer Exceltabelle, was die Nutzung des Falldatenblatts wegen dessen Beschränkungen etwas erschwert. 

Ich würde das Falldatenblatt sehr gern nutzen und hoffe, dass mein Vorschlag Gehör findet :)

**Comment by j-dimension** [comment]
eine feste Menge weiterer Positionen – Sonstige 1..3 o.ä. mit festem Platzhalter.

**Comment by j-dimension** [comment]
Ich habe als schnelle Lösung jetzt erstmal eine Möglichkeit hinzugefügt, die sonstigen Positionen beschreiben zu können, als einfache Auflistung / Freitext: 

![grafik](https://user-images.githubusercontent.com/3729754/102275478-ba7c9a00-3f25-11eb-9ee7-69fb1d367243.png)

**Comment by iradraconis** [comment]
das sieht schon mal gut aus. Um die Funktionalität vollständig zu machen, würde dann aber nicht auch ein Feld "sonstiges (auflisten) => reguliert" Sinn machen?

**Comment by j-dimension** [comment]
Das wäre dann ebenfalls ein Freitextfeld, um die regulierten Gegenstände aufzulisten?

**Comment by iradraconis** [comment]
> Das wäre dann ebenfalls ein Freitextfeld, um die regulierten Gegenstände aufzulisten?

Ja, ich meine das würde die Funktionalität und den Überblick erhöhen.
