### ISSUE TITLE
Verkehrsunfalldaten: Berücksichtigung Vorschäden/Neu-für-alt-Abzug

### ISSUE THREAD

**Issue by Linkki2021** [jlawyerorg/j-lawyer-forms#93]
Über der merkantilen Wertminderung würde inhaltlich eine weitere Zeile Sinn ergeben:

Abzüglich Neu-für-alt (Nfa) --> Betrag, zzgl. MwSt., reguliert (braucht man in dem Fall nicht bzw. kann ausgegraut auf 0,00 gesetzt werden), Differenz

Die Zeile müsste in den Schadensummen abgezogen werden (rechnerisch analog "Abzüglich Restwert").

Ab einer gewissen Stückzahl gibt es Nfa dann doch relativ häufig, so dass die Umsetzung nicht einfach nur einen quasi nie auftretenden Sonderfall abdeckt, und damit m.E. allgemein sinnstiftend ist.

**Comment by j-dimension** [comment]
Hierzu brauche ich bei Gelegenheit fachlichen Input, @Linkki2021
